/// \file
/// \ingroup tutorial_io
/// \notebook -nodraw
/// Example of script to loop on all the objects of a ROOT file directory
/// and print on Postscript all TH1 derived objects.
/// This script uses the file generated by tutorial hsimple.C
///
/// \macro_image
/// \macro_code
///
/// \author Rene Brun

void loopdir() {
   TFile *f1 = TFile::Open("/Users/claudeapruneau/Documents/GitHub/WAC/OutputFiles//PYTHIA_softOnHardOff_Singles_LUMP_Wide_MB_Sum0_99.root");
   TIter keyList(f1->GetListOfKeys());
   TKey *key;
  TCanvas c1;
   c1.Print("hsimple.pdf[");
   while ((key = (TKey*)keyList())) {
      TClass *cl = gROOT->GetClass(key->GetClassName());
      if (!cl->InheritsFrom("TH1")) continue;
     TH1 *h = (TH1*)key->ReadObj();
     TH1 *hc = (TH1*) h->Clone();

     cout << hc->GetName() << endl;

           hc->Draw();
      c1.Print("hsimple.pdf");
   }
   c1.Print("hsimple.pdf]");
}

